### ISSUE TITLE
Tomcat version out of date

### ISSUE THREAD

**Issue by golpa** [OPENDAP/hyrax-docker#31]
The hyrax image posted on the docker hub for tag `1.16.2` uses tomcat version `7.0.76`. That version has a long list of vulnerabilities. Is this something that can be updated to the latest version `7.0.105`?

**Comment by ndp-opendap** [comment]
The Hyrax docker container is based on CentOS-7 latest, and (as you mentioned) the latest version of Tomcat available via yum on that image is currently 7.0.76. I am actually a bit surprised that the CentOS team have not addressed this yet. I'll see what I can figure out - moving to a Tomcat distribution directly from Apache can be done, but it will involve a fair bit of fooling around with the Docker project to get it sorted. By which I mean I have to carve out the time to work on it.

**Comment by ndp-opendap** [comment]
I wanted to write back and let you know that I have learned some things about this issue.

The issues that I believe that are the actual points of concern in this are:

     • CVE-2018-1336 Apache Tomcat - Denial of Service 
     • CVE-2018-8034 Apache Tomcat - Security Constraint Bypass 

These both appear to have been assessed by the RedHat/CentOS team. 

It looks like CVE-2018-1336 was found to have "Important Impact" and was fixed in the yum distributed release beginning with Tomcat 7.0.76-8.el7_5. See: https://urldefense.proofpoint.com/v2/url?u=https-3A__access.redhat.com_security_cve_cve-2D2018-2D1336&d=DwIFaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=fgUbRt-HF-E8NHlSFg9SQT4wFtoy80-cOKmkOmEoC0U&m=ycXGbNCcdJSOXauVCqbKPJgi1Tq6QSjF7WyfeEeKMGU&s=ETAtJjWSIqjupePTu09j62-Y9H_TAz7NGeT1Y8tllVI&e= 

   In the case of CVE-2018-8034 it was classified as "Low Impact" and has not been addressed at this time. See: https://urldefense.proofpoint.com/v2/url?u=https-3A__access.redhat.com_security_cve_cve-2D2018-2D8034&d=DwIFaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=fgUbRt-HF-E8NHlSFg9SQT4wFtoy80-cOKmkOmEoC0U&m=ycXGbNCcdJSOXauVCqbKPJgi1Tq6QSjF7WyfeEeKMGU&s=KDpAicbqgPpyidoh0_0OcbuIbJafwxeABhSPcD1JY9A&e= 

I found this exchange in the CeNTOS forums very helpful:

       https://urldefense.proofpoint.com/v2/url?u=https-3A__forums.centos.org_viewtopic.php-3Ff-3D51-26t-3D68826-26p-3D288990-26hilit-3Dtomcat-23p288990&d=DwIFaQ&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=fgUbRt-HF-E8NHlSFg9SQT4wFtoy80-cOKmkOmEoC0U&m=ycXGbNCcdJSOXauVCqbKPJgi1Tq6QSjF7WyfeEeKMGU&s=vUa4t8CAu7r2AhW5J__unDIO9nJ89OQqtLsHaB4eWUs&e= 

The current version of Tomcat in CentOS yum is

     Available Packages
     Name        : tomcat
     Arch        : noarch
     Version     : 7.0.76
     Release     : 12.el7_8

Which, based on the forum page above, contains the fix for CVE-2018-1336.


Please let me know if your concerns have been addressed.

**Comment by golpa** [comment]
@ndp-opendap that makes sense! thanks for looking into it.

**Comment by ndp-opendap** [comment]
cool - I'll close this now. Thanks for your patience.
